module.exports = {
	"alt metal": ["fear", "flying", "freedom", "loss", "monsters", "mysticism", "politics", "rebellion", "scaring", "space", "the city", "the night", "war"],
	"ballad": ["fear", "flying", "freedom", "girls names", "life", "loss", "love", "rainbow", "running", "the night"],
	"bluegrass": ["freedom", "life", "loss", "love", "mysticism", "running"],
	"blues": ["being tough", "freedom", "life", "loss", "love", "rebellion", "running"],
	"bollywood": ["clothes", "dancing", "fun", "girls names", "life", "loss", "love", "partying"],
	"brit pop": ["clothes", "freedom", "fun", "girls names", "life", "love", "partying", "shoes", "the city"],
	"cabaret": ["flying", "fun", "girls names", "life", "love", "the night"],
	"country": ["animals", "cars", "dancing", "freedom", "life", "loss", "love", "patriotism", "rainbows", "shoes", "war"],
	"dance": ["boasting", "dancing", "freedom", "fun", "life", "love", "partying", "running", "shoes", "space"],
	"death metal": ["animals", "fear", "loss", "monsters", "mysticism", "scaring", "the city", "war"],
	"disco": ["clothes", "dancing", "freedom", "fun", "life", "love", "partying", "running", "shoes", "the city", "the night"],
	"drum and bass": ["animals", "being tough", "dancing", "fear", "flying", "life", "scaring", "the night"],
	"dub": ["crime", "dancing", "flying", "freedom", "partying", "rebellion", "running", "scaring", "war"],
	"dub step": ["being tough", "dancing", "flying", "freedom", "loss", "partying", "rebellion", "running", "scaring", "space", "the city", "the night", "war"],
	"electro pop": ["animals", "fun", "life", "love", "monsters", "partying", "rainbows"],
	"electronica": ["dancing", "freedom", "life", "partying", "space", "the night", "war"],
	"emo": ["being tough", "fear", "life", "loss", "love", "rebellion", "scaring", "the night"],
	"folk": ["animals", "flying", "life", "loss", "love", "mysticism", "politics", "rainbows", "space", "war"],
	"funk": ["being tough", "flying", "freedom", "girls names", "partying", "politics", "running"],
	"gangsta boogie": ["being tough", "boasting", "crime", "fear", "freedom", "life", "loss", "partying", "politics", "rebellion", "running", "scaring", "the city", "the night", "war"],
	"glam rock": ["boasting", "dancing", "flying", "freedom", "fun", "girls names", "love", "partying", "the night"],
	"grunge": ["being tough", "life", "loss", "rebellion", "the night"],
	"hardcore punk": ["being tough", "freedom", "fun", "loss", "partying", "politics", "rebellion", "scaring"],
	"hip hop": ["being tough", "boasting", "cars", "clothes", "crime", "life", "partying", "rebellion", "shoes", "the city"],
	"house": ["boasting", "freedom", "fun", "girls names", "love", "partying", "space", "the night"],
	"j-pop": ["animals", "flying", "life", "love", "mysticism"],
	"jazz": ["dancing", "freedom", "life", "love", "shoes", "the city"],
	"k-pop": ["animals", "dancing", "flying", "fun", "girls names", "life", "love", "partying", "rainbows", "shoes", "the night"],
	"latin": ["dancing", "freedom", "girls names", "life", "love", "partying"],
	"math rock": ["flying", "life", "loss", "love", "rebellion", "the night"],
	"metal": ["being tough", "monsters", "mysticism", "rebellion", "scaring", "war"],
	"pop": ["clothes", "dancing", "fun", "girls names", "life", "loss", "love", "partying", "rainbows"],
	"punk": ["being tough", "freedom", "partying", "the city", "war"],
	"r&b": ["boasting", "clothes", "dancing", "fun", "girls names", "life", "love", "partying", "shoes"],
	"reggae": ["animals", "dancing", "flying", "freedom", "fun", "girls names", "love", "partying", "patriotism", "politics", "rebellion", "running", "war"],
	"rock": ["cars", "fear", "flying", "fun", "girls names", "love", "monsters", "partying"],
	"rockabilly": ["cars", "crime", "fun", "girls names", "life", "love", "shoes"],
	"roots": ["freedom", "life", "love", "patriotism", "politics", "rebellion", "the night", "war"],
	"ska": ["being tough", "freedom", "fun", "love", "politics"],
	"skate punk": ["being tough", "boasting", "clothes", "fear", "freedom", "life", "partying", "rebellion", "running", "the night"],
	"soft rock": ["freedom", "girls names", "life", "loss", "love", "partying", "patriotism", "running", "the night"],
	"soul": ["crime", "dancing", "fun", "girls names", "life", "love", "rainbows"],
	"speed metal": ["animals", "being tough", "fear", "monsters", "mysticism", "scaring", "the night", "war"],
	"stadium rock": ["being tough", "fear", "freedom", "loss", "partying", "the night"],
	"techno": ["dancing", "flying", "freedom", "fun", "life", "love", "partying", "running", "space", "the night"],
	"trip hop": ["fear", "flying", "freedom", "fun", "girls names", "life", "love", "running", "scaring", "space", "the night"],
	"urban": ["being tough", "boasting", "cars", "clothes", "crime", "flying", "girls names", "love", "partying", "rebellion", "the city"]
}