module.exports = {
	"alt metal": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 3},
	"ballad": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 2,"keys": 1},
	"bluegrass": {"vocals": 2,"drums": 1,"bass": 1,"guitar": 1,"horns": 1},
	"blues": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 2,"keys": 1},
	"bollywood": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 1,"keys": 2},
	"brit pop": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 2,"keys": 1},
	"cabaret": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 1,"horns": 1,"keys": 1},
	"country": {"vocals": 2,"drums": 1,"bass": 1,"guitar": 2},
	"dance": {"vocals": 1,"rapper": 1,"bass": 1,"keys": 2,"decks": 1},
	"death metal": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 3},
	"drum and bass": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 1,"horns": 2},
	"dub": {"vocals": 1,"drums": 1,"guitar": 1,"keys": 2,"decks": 1},
	"e-pop": {"vocals": 1,"drums": 1,"bass": 1,"keys": 2,"decks": 1},
	"electronica": {"vocals": 1,"drums": 1,"bass": 1,"keys": 2,"decks": 1},
	"emo": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 2,"decks": 1},
	"folk": {"vocals": 2,"drums": 1,"bass": 1,"guitar": 1,"horns": 1},
	"funk": {"vocals": 2,"drums": 1,"bass": 1,"guitar": 1,"horns": 1},
	"gansta rap": {"rapper": 2,"drums": 1,"bass": 1,"guitar": 1,"decks": 1},
	"glam rock": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 3},
	"grunge": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 2,"keys": 1},
	"hip-hop": {"rapper": 1,"drums": 1,"bass": 1,"guitar": 1,"horns": 1,"decks": 1},
	"house": {"vocals": 2,"drums": 1,"bass": 1,"keys": 1,"decks": 1},
	"j-pop": {"vocals": 3,"drums": 1,"bass": 1,"keys": 1},
	"jazz": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 1,"horns": 1,"keys": 1},
	"k-pop": {"vocals": 2,"drums": 1,"bass": 1,"keys": 1,"decks": 1},
	"latin": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 1,"horns": 2,"undefined": 0},
	"math rock": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 2,"keys": 1},
	"metal": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 3},
	"pop": {"vocals": 2,"drums": 1,"bass": 1,"keys": 1,"decks": 1},
	"punk": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 3},
	"reggae": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 1,"horns": 1,"keys": 1},
	"rnb": {"vocals": 2,"drums": 1,"bass": 1,"keys": 1,"decks": 1},
	"rock": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 2,"keys": 1},
	"rockabilly": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 2,"undefined": 0,"keys": 1},
	"roots": {"vocals": 2,"drums": 1,"bass": 1,"guitar": 2},
	"ska": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 1,"horns": 2},
	"skate punk": {"vocals": 1,"rapper": 1,"drums": 1,"bass": 1,"guitar": 1,"decks": 1},
	"soft rock": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 2,"keys": 1},
	"soul": {"vocals": 2,"drums": 1,"bass": 1,"guitar": 1,"horns": 1},
	"speed metal": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 3},
	"stadium rock": {"vocals": 1,"drums": 1,"bass": 1,"guitar": 2,"keys": 1},
	"techno": {"vocals": 1,"bass": 1,"guitar": 1,"keys": 2,"decks": 1},
	"urban": {"vocals": 2,"drums": 1,"bass": 1,"keys": 1,"decks": 1}
}
